export const PAISES = {
  AF: "Afganistán",
  AL: "Albania",
  DE: "Alemania",
  AD: "Andorra",
  AO: "Angola",
  AI: "Anguila",
  AQ: "Antártida",
  AG: "Antigua y Barbuda",
  SA: "Arabia Saudita",
  DZ: "Argelia",
  AR: "Argentina",
  AM: "Armenia",
  AW: "Aruba",
  AU: "Australia",
  AT: "Austria",
  AZ: "Azerbaiyán",
  BS: "Bahamas",
  BD: "Bangladés",
  BB: "Barbados",
  BH: "Baréin",
  BE: "Bélgica",
  BZ: "Belice",
  BJ: "Benín",
  BM: "Bermudas",
  BY: "Bielorrusia",
  BO: "Bolivia",
  BQ: "Caribe Neerlandés",
  BA: "Bosnia y Herzegovina",
  BW: "Botsuana",
  BR: "Brasil",
  BN: "Brunéi",
  BG: "Bulgaria",
  BF: "Burkina Faso",
  BI: "Burundi",
  BT: "Bután",
  CV: "Cabo Verde",
  KH: "Camboya",
  CM: "Camerún",
  CA: "Canadá",
  QA: "Catar",
  TD: "Chad",
  CL: "Chile",
  CN: "China",
  CY: "Chipre",
  CO: "Colombia",
  KM: "Comoras",
  CG: "Congo",
  CD: "Congo (Rep. Dem.)",
  KP: "Corea del Norte",
  KR: "Corea del Sur",
  CI: "Costa de Marfil",
  CR: "Costa Rica",
  HR: "Croacia",
  CU: "Cuba",
  CW: "Curazao",
  DK: "Dinamarca",
  DM: "Dominica",
  EC: "Ecuador",
  EG: "Egipto",
  SV: "El Salvador",
  AE: "Emiratos Árabes Unidos",
  ER: "Eritrea",
  SK: "Eslovaquia",
  SI: "Eslovenia",
  ES: "España",
  US: "Estados Unidos",
  EE: "Estonia",
  SZ: "Esuatini",
  ET: "Etiopía",
  PH: "Filipinas",
  FI: "Finlandia",
  FJ: "Fiyi",
  FR: "Francia",
  GA: "Gabón",
  GM: "Gambia",
  GE: "Georgia",
  GH: "Ghana",
  GI: "Gibraltar",
  GD: "Granada",
  GR: "Grecia",
  GL: "Groenlandia",
  GP: "Guadalupe",
  GU: "Guam",
  GT: "Guatemala",
  GF: "Guayana Francesa",
  GG: "Guernsey",
  GY: "Guyana",
  GN: "Guinea",
  GQ: "Guinea Ecuatorial",
  GW: "Guinea-Bisáu",
  HT: "Haití",
  HN: "Honduras",
  HK: "Hong Kong",
  HU: "Hungría",
  IN: "India",
  ID: "Indonesia",
  IR: "Irán",
  IQ: "Irak",
  IE: "Irlanda",
  IS: "Islandia",
  IL: "Israel",
  IT: "Italia",
  JM: "Jamaica",
  JP: "Japón",
  JE: "Jersey",
  JO: "Jordania",
  KZ: "Kazajistán",
  KE: "Kenia",
  KG: "Kirguistán",
  KI: "Kiribati",
  KW: "Kuwait",
  LA: "Laos",
  LS: "Lesoto",
  LV: "Letonia",
  LB: "Líbano",
  LR: "Liberia",
  LY: "Libia",
  LI: "Liechtenstein",
  LT: "Lituania",
  LU: "Luxemburgo",
  MO: "Macao",
  MG: "Madagascar",
  MY: "Malasia",
  MW: "Malaui",
  MV: "Maldivas",
  ML: "Malí",
  MT: "Malta",
  MA: "Marruecos",
  MQ: "Martinica",
  MU: "Mauricio",
  MR: "Mauritania",
  YT: "Mayotte",
  MX: "México",
  FM: "Micronesia",
  MD: "Moldavia",
  MC: "Mónaco",
  MN: "Mongolia",
  ME: "Montenegro",
  MZ: "Mozambique",
  MM: "Myanmar",
  NA: "Namibia",
  NR: "Nauru",
  NP: "Nepal",
  NI: "Nicaragua",
  NE: "Níger",
  NG: "Nigeria",
  NU: "Niue",
  NF: "Isla Norfolk",
  NO: "Noruega",
  NC: "Nueva Caledonia",
  NZ: "Nueva Zelanda",
  OM: "Omán",
  NL: "Países Bajos",
  PK: "Pakistán",
  PW: "Palaos",
  PA: "Panamá",
  PG: "Papúa Nueva Guinea",
  PY: "Paraguay",
  PE: "Perú",
  PN: "Islas Pitcairn",
  PF: "Polinesia Francesa",
  PL: "Polonia",
  PT: "Portugal",
  PR: "Puerto Rico",
  GB: "Reino Unido",
  CF: "República Centroafricana",
  CZ: "República Checa",
  DO: "República Dominicana",
  RE: "Reunión",
  RW: "Ruanda",
  RO: "Rumania",
  RU: "Rusia",
  EH: "Sahara Occidental",
  WS: "Samoa",
  AS: "Samoa Americana",
  BL: "San Bartolomé",
  KN: "San Cristóbal y Nieves",
  SM: "San Marino",
  MF: "San Martín",
  PM: "San Pedro y Miquelón",
  VC: "San Vicente y las Granadinas",
  SH: "Santa Elena",
  LC: "Santa Lucía",
  ST: "Santo Tomé y Príncipe",
  SN: "Senegal",
  RS: "Serbia",
  SC: "Seychelles",
  SL: "Sierra Leona",
  SG: "Singapur",
  SX: "Sint Maarten",
  SY: "Siria",
  SO: "Somalia",
  LK: "Sri Lanka",
  ZA: "Sudáfrica",
  SD: "Sudán",
  SS: "Sudán del Sur",
  SE: "Suecia",
  CH: "Suiza",
  SR: "Surinam",
  TH: "Tailandia",
  TW: "Taiwán",
  TZ: "Tanzania",
  TJ: "Tayikistán",
  IO: "Territorio Británico del Océano Índico",
  PS: "Palestina",
  TL: "Timor Oriental",
  TG: "Togo",
  TK: "Tokelau",
  TO: "Tonga",
  TT: "Trinidad y Tobago",
  TN: "Túnez",
  TM: "Turkmenistán",
  TR: "Turquía",
  TV: "Tuvalu",
  UA: "Ucrania",
  UG: "Uganda",
  UY: "Uruguay",
  UZ: "Uzbekistán",
  VU: "Vanuatu",
  VA: "Vaticano",
  VE: "Venezuela",
  VN: "Vietnam",
  WF: "Wallis y Futuna",
  YE: "Yemen",
  ZM: "Zambia",
  ZW: "Zimbabue"
}